//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendor_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_entry
    {
        public int Id { get; set; }
        public string V_C_Type { get; set; }
        public string V_C_Name { get; set; }
        public string Firm_Name { get; set; }
        public string Area { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Tahasil { get; set; }
        public string Dist { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string Dom_Foreign { get; set; }
        public string Con_Per_Name { get; set; }
        public string Con_Number { get; set; }
        public string Con_Email { get; set; }
        public string Conn_Int_Plnt { get; set; }
        public string Supp_Type { get; set; }
        public string GSTIN_No { get; set; }
        public byte[] GSTIN_Cert { get; set; }
        public string PAN_NO { get; set; }
        public byte[] Pan_Card { get; set; }
        public string Aadhar_No { get; set; }
        public byte[] Aadhar_Card { get; set; }
        public string MSME_Appr { get; set; }
        public byte[] MSME_Cert { get; set; }
        public string Pay_Term { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Branch { get; set; }
        public string Bank_IFSC_Code { get; set; }
        public string Bank_Hol_Name { get; set; }
        public string Bank_Acc_No { get; set; }
        public byte[] Bank_Chck_Copy { get; set; }
        public Nullable<System.DateTime> V_C_Date { get; set; }
    }
}
