//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendor_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string user_type { get; set; }
        public Nullable<int> regional_manager_id { get; set; }
    
        public virtual regional_manager regional_manager { get; set; }
    }
}
